# Generated by Django 2.0.4 on 2018-05-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.IntegerField(db_column='CID', primary_key=True, serialize=False)),
                ('cname', models.CharField(db_column='CName', max_length=20)),
                ('rid', models.IntegerField(db_column='RID')),
                ('sid', models.IntegerField(db_column='SID')),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Courseselect',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField(db_column='CID')),
                ('sid', models.IntegerField(db_column='SID')),
            ],
            options={
                'db_table': 'CourseSelect',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rid', models.IntegerField(db_column='RID', primary_key=True, serialize=False)),
                ('rno', models.CharField(db_column='Rno', max_length=20)),
                ('mmac', models.CharField(db_column='MMac', max_length=20)),
            ],
            options={
                'db_table': 'Room',
            },
        ),
    ]
