CREATE TABLE User(
 SID INTEGER PRIMARY KEY,
 SName VARCHAR(20) NOT NULL,
 Role INTEGER NOT NULL,
 Sno VARCHAR(12) NOT NULL,
 Phone VARCHAR(11) NOT NULL,
 Password VARCHAR(20) NOT NULL,
 Mac VARCHAR(20) NOT NULL
);

CREATE TABLE Course(
 CID INTEGER PRIMARY KEY,
 CName VARCHAR(20) NOT NULL,
 RID INTEGER NOT NULL,
 SID INTEGER NOT NULL
);

CREATE TABLE CourseSelect(
 CID INTEGER NOT NULL,
 SID INTEGER NOT NULL
);

CREATE TABLE Room(
 RID INTEGER PRIMARY KEY,
 MMac VARCHAR(20) NOT NULL
);

